<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MinecraftManager.Core/MinecraftManager.Core.csproj" />
    <ProjectReference Include="../MinecraftManager.Infrastructure/MinecraftManager.Infrastructure.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Portraits.png" />
    <EmbeddedResource Include="Assets\Portraits.png" />
  </ItemGroup>
</Project>
