<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MinecraftManager.Core/MinecraftManager.Core.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="SharpCompress" />
  </ItemGroup>
</Project>
