<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Minio" />
    <ProjectReference Include="..\..\src\MinecraftManager.Server.Api\MinecraftManager.Server.Api.csproj" />
  </ItemGroup>
</Project>
